### ISSUE TITLE
request: Please stop spamming in the fontawesome-iconpicker Chrome extension

### ISSUE THREAD

**Issue by itsjavi** [CS76/fontawesome-icon-finder#1]
Hello this is more a request and I would like to kindly ask you that please stop spamming about this project in the "Help" section of the [Chrome extension](https://chrome.google.com/webstore/detail/font-awesome-icon-picker/mcepmpclbgahgbpcgbmnpplcfmlaiopm/support?hl=es&gl=DE) site of the [`fontawesome-iconpicker`](http://farbelous.github.io/fontawesome-iconpicker/) library.

It's not only not fair play, but it also confuses people using the extension that are looking for help.

Thanks for understanding.

**Comment by CS76** [comment]
Hi, Since your plugin haven't been working since February, I thought it would be helpful for people to point them to a working resource. Anyways since you consider it a spam, I am deleting all the comments. Sorry for any inconvenience caused. Thanks 👍
